/**
 * @fileoverview FlowDev  -  Intelligent CLI tool
 * @module flowdev
 * @version 1.0.5
 * * @license MIT
 * Copyright (c) 2026 FlowDev Technologies.
 * * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 */

import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { logger } from '../../utils/logger.js';

const SCAN_EXTENSIONS = ['.js', '.jsx', '.ts', '.tsx', '.vue', '.svelte', '.json', '.php', '.py', '.go', '.java'];
const IGNORE_DIRS = ['node_modules', '.git', 'dist', 'build', 'coverage', '.next', 'vendor'];


async function getFiles(dir) {
  const subdirs = await fs.readdir(dir);
  const files = await Promise.all(subdirs.map(async (subdir) => {
    const res = path.resolve(dir, subdir);
    
    if (IGNORE_DIRS.includes(subdir)) return [];

    const stat = await fs.stat(res);
    
    if (stat.isDirectory()) {
      return getFiles(res); 
    } else {
      
      if (SCAN_EXTENSIONS.includes(path.extname(res))) {
        return res;
      }
      return [];
    }
  }));
  return files.reduce((a, f) => a.concat(f), []);
}

function extractEnvVars(content) {
  const vars = new Set();
  
 
  const regex = /\b(?:process\.env\.|import\.meta\.env\.|process\.env\[['"])([A-Z_][A-Z0-9_]*)\b/g;
  
  let match;
  while ((match = regex.exec(content)) !== null) {
   
    if (match[1] && match[1] !== 'NODE_ENV') { 
      vars.add(match[1]);
    }
  }
  
  return Array.from(vars);
}

export async function envCommand() {
  const spinner = ora(chalk.cyan('Scanning project for environment variables...')).start();

  try {
    const rootDir = process.cwd();
    
    
    const files = await getFiles(rootDir);
    spinner.text = chalk.cyan(`Analyzing ${files.length} files...`);

    const allEnvVars = new Set();

    
    for (const file of files) {
      try {
        const content = await fs.readFile(file, 'utf-8');
        const vars = extractEnvVars(content);
        vars.forEach(v => allEnvVars.add(v));
      } catch (err) {
       
      }
    }

    if (allEnvVars.size === 0) {
      spinner.warn(chalk.yellow('No environment variables found in code.'));
      return;
    }

    
    const sortedVars = Array.from(allEnvVars).sort();
    let envContent = `# Auto-generated by FlowDev\n# Environment Variables Example\n\n`;
    
    sortedVars.forEach(variable => {
      envContent += `${variable}=\n`;
    });

    const outputPath = path.join(rootDir, '.env.example');

    if (await fs.pathExists(outputPath)) {

        const oldContent = await fs.readFile(outputPath, 'utf-8');
        const existingLines = oldContent.split('\n');
        
        let newCount = 0;
        let appendContent = "\n# New variables detected by FlowDev:\n";
        
        sortedVars.forEach(variable => {
            if (!oldContent.includes(variable + '=')) {
                appendContent += `${variable}=\n`;
                newCount++;
            }
        });

        if (newCount > 0) {
            await fs.appendFile(outputPath, appendContent);
            spinner.succeed(chalk.green(`Updated .env.example with ${newCount} new variables!`));
        } else {
            spinner.succeed(chalk.green('.env.example is already up to date.'));
        }

    } else {
       
        await fs.writeFile(outputPath, envContent);
        spinner.succeed(chalk.green(`Created .env.example with ${allEnvVars.size} variables!`));
    }

   
    console.log(chalk.gray('\nDetected variables:'));
    sortedVars.forEach(v => console.log(chalk.blue(`- ${v}`)));
    console.log('');

  } catch (error) {
    spinner.stop();
    logger.error(`Error generating .env file: ${error.message}`);
  }
}